// <auto-generated />
namespace Sistema.Ifsp.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class alerandoclassefornecedor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alerandoclassefornecedor));
        
        string IMigrationMetadata.Id
        {
            get { return "201511162017088_alerando-classe-fornecedor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
